### ISSUE TITLE
What files are you looking for?

### ISSUE THREAD

**Issue by ssolson** [Data-Only-Greater/SNL-Delft3D-CEC-Verify#1]
https://github.com/H0R5E/SNL-Delft3D-CEC-Verify/blob/89dbfe4548c1f62c88b59b3a1616d3c3d9386f57/README.md?plain=1#L57

Hey Mat on this line above from the README am I trying to point to:
`C:\Program Files (x86)\Deltares\Delft3D FM Suite 2020.01 HMWQ (1.6.0.46002)\plugins\DeltaShell.Dimr\kernels\x64\dflowfm\bin`

So that it can find: `dflowfm.dll`, `dflowfm-cli.exe`, and `dfmoutput.exe`?

**Comment by H0R5E** [comment]
Sterling, to answer your question directly, the `Report` class is initialized with the `src\bin` folder created when you compile the code. It then calls the `x64\dflowfm\scripts\run_dflowfm.bat` script on Windows and the `run_dflowfm.sh` script in Linux. I've found these scripts to be the easiest entry point for calling Delft3D.

Less direct answer, I wanted it to be easy to run the example without having to change the script, but I had only considered using the binaries compiled in the source code, not in the distributed package you are trying to use. I've changed the example (and README) so that you now set the `D3D_BIN` environmental variable to specify the `bin` folder (before I was asking for the source code root). So, now, for the distributed package, using Powershell, the setting command would be:

```
> $env:D3D_BIN = "C:\Program Files (x86)\Deltares\Delft3D FM Suite 2020.01 HMWQ (1.6.0.46002)\plugins\DeltaShell.Dimr\kernels"
```

assuming the same installation location as the one you specified above.

From a design perspective, automatic discovery of the location of the Delft3D binaries is pretty hard. I don't try to do any discovery in the package itself, I just added some into the example to try and make it easier (see the `get_d3d_bin_path` function at the top of `basic.py`). If you have any suggestions around this issue, I'd be interested to hear them.

**Comment by H0R5E** [comment]
@ssolson, note that I have moved this repo so that I can use the CI with pull requests from my personal account.

**Comment by ssolson** [comment]
Mat I am a bit confused. Above it looks like you say I can use my distribution and I set the variable as described. I then head to basiy.py but it does not run. I cannot tell if the path is not working or if I have done something incorrectly running the case and it cannot find the case files.

```
(_snld3d) C:\Users\sterl\Codes\SNL-Delft3D-CEC-Verify\examples>python basic.py
Traceback (most recent call last):
  File "C:\Users\sterl\Codes\SNL-Delft3D-CEC-Verify\examples\basic.py", line 39, in <module>
    runner(tmpdirname)
  File "c:\users\sterl\codes\snl-delft3d-cec-verify\src\snl_d3d_cec_verify\runner.py", line 31, in __call__
    run_dflowfm(self.d3d_bin_path,
  File "c:\users\sterl\codes\snl-delft3d-cec-verify\src\snl_d3d_cec_verify\runner.py", line 58, in run_dflowfm
    sp = subprocess.Popen([run_dflowfm_path, "FlowFM.mdu"],
  File "C:\Users\sterl\anaconda3\envs\_snld3d\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\sterl\anaconda3\envs\_snld3d\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

(_snld3d) C:\Users\sterl\Codes\SNL-Delft3D-CEC-Verify\examples>echo %D3DBIN%
C:\Program Files (x86)\Deltares\Delft3D FM Suite 2020.01 HMWQ (1.6.0.46002)\plugins\DeltaShell.Dimr\kernels
```

**Comment by H0R5E** [comment]
Sterling, I'm really sorry, I've clearly done something wrong. Do you have the file in trying to point at in your Delft3D tree? I need to provide a better error message when this happens for sure. I'm done for today but I'll add it tomorrow.

**Comment by H0R5E** [comment]
Sterling, the variable is called D3D_BIN with an underscore. I think you don't have the underscore in your environment var.

**Comment by ssolson** [comment]
Ahh that was it. ty. I got the report running.
